name: Ansible Docsite CI

"on":
  schedule:
    # Daily
    - cron: "23 7 * * *"
  push:
    branches-ignore:
      - 'patchback/**'
      - 'pip-compile/**'
  pull_request:
    types:
    - opened  # default
    - synchronize  # default
    - reopened  # default
    - ready_for_review  # used in PRs created from GitHub Actions workflows
  workflow_dispatch:

jobs:
  nox:
    uses: ./.github/workflows/reusable-nox.yml

  check:
    if: always()

    needs:
      - nox

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
